---
sudo: false
language: ruby
cache: bundler
rvm:
- jruby-1.7.25
before_install:
- git clone -b feature/event_interface https://github.com/elastic/logstash
before_script:
- bundle exec rake vendor
- bundle exec rake install_jars
script: bundle exec rspec && bundle exec rspec --tag integration
jdk: oraclejdk8
